-- MySQL Script generated by MySQL Workbench
-- jue 23 mar 2023 16:30:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petanca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `petanca` ;

-- -----------------------------------------------------
-- Schema petanca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petanca` ;
USE `petanca` ;

-- -----------------------------------------------------
-- Table `petanca`.`stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petanca`.`stadium` (
  `idstadium` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(120) NULL,
  `capacity` INT NOT NULL DEFAULT 10,
  PRIMARY KEY (`idstadium`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petanca`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petanca`.`team` (
  `idteam` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creation_date` DATE NULL,
  `idcaptain` INT UNSIGNED NULL,
  `idstadium` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idteam`),
  INDEX `fk_team_player_idx` (`idcaptain` ASC) VISIBLE,
  INDEX `fk_team_stadium1_idx` (`idstadium` ASC) VISIBLE,
  CONSTRAINT `fk_team_player`
    FOREIGN KEY (`idcaptain`)
    REFERENCES `petanca`.`player` (`idplayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_stadium1`
    FOREIGN KEY (`idstadium`)
    REFERENCES `petanca`.`stadium` (`idstadium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petanca`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petanca`.`player` (
  `idplayer` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT UNSIGNED NOT NULL,
  `idteam` INT UNSIGNED NULL,
  PRIMARY KEY (`idplayer`),
  INDEX `fk_player_team1_idx` (`idteam` ASC) VISIBLE,
  CONSTRAINT `fk_player_team1`
    FOREIGN KEY (`idteam`)
    REFERENCES `petanca`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petanca`.`tournament`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petanca`.`tournament` (
  `idtournament` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idtournament`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petanca`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petanca`.`game` (
  `idgame` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `idstadium` INT UNSIGNED NOT NULL,
  `idtournament` INT UNSIGNED NULL,
  PRIMARY KEY (`idgame`),
  INDEX `fk_match_stadium1_idx` (`idstadium` ASC) VISIBLE,
  INDEX `fk_match_tournament1_idx` (`idtournament` ASC) VISIBLE,
  CONSTRAINT `fk_match_stadium1`
    FOREIGN KEY (`idstadium`)
    REFERENCES `petanca`.`stadium` (`idstadium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_match_tournament1`
    FOREIGN KEY (`idtournament`)
    REFERENCES `petanca`.`tournament` (`idtournament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petanca`.`team_has_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petanca`.`team_has_game` (
  `idteam` INT UNSIGNED NOT NULL,
  `idgame` INT UNSIGNED NOT NULL,
  `position` INT NULL,
  PRIMARY KEY (`idteam`, `idgame`),
  INDEX `fk_team_has_match_match1_idx` (`idgame` ASC) VISIBLE,
  INDEX `fk_team_has_match_team1_idx` (`idteam` ASC) VISIBLE,
  UNIQUE INDEX `uq_team_has_match_position` (`idgame` ASC, `position` ASC) VISIBLE,
  CONSTRAINT `fk_team_has_match_team1`
    FOREIGN KEY (`idteam`)
    REFERENCES `petanca`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_match_match1`
    FOREIGN KEY (`idgame`)
    REFERENCES `petanca`.`game` (`idgame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petanca`.`tournament_has_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petanca`.`tournament_has_team` (
  `idtournament` INT UNSIGNED NOT NULL,
  `idteam` INT UNSIGNED NOT NULL,
  `points` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`idtournament`, `idteam`),
  INDEX `fk_tournament_has_team_team1_idx` (`idteam` ASC) VISIBLE,
  INDEX `fk_tournament_has_team_tournament1_idx` (`idtournament` ASC) VISIBLE,
  CONSTRAINT `fk_tournament_has_team_tournament1`
    FOREIGN KEY (`idtournament`)
    REFERENCES `petanca`.`tournament` (`idtournament`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tournament_has_team_team1`
    FOREIGN KEY (`idteam`)
    REFERENCES `petanca`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `petanca` ;

-- -----------------------------------------------------
-- procedure setwinner
-- -----------------------------------------------------

DELIMITER $$
USE `petanca`$$
CREATE PROCEDURE `setwinner` (IN gid INT)
BEGIN
UPDATE team_has_game
SET position=1
WHERE idgame=gid
AND idteam IN(
SELECT * FROM
	(
		SELECT team.idteam
		FROM team
		JOIN player ON team.idteam=player.idteam
		WHERE team.idteam IN (
			SELECT team.idteam
			FROM team
			JOIN team_has_game as thg ON thg.idteam=team.idteam
			JOIN game ON game.idgame=thg.idgame
			WHERE game.idgame=gid
		)
		GROUP BY team.idteam
		ORDER BY AVG(player.age) DESC
		LIMIT 1
	) as t1
)
;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure setloser
-- -----------------------------------------------------

DELIMITER $$
USE `petanca`$$
CREATE PROCEDURE `setloser` (IN gid INT)
BEGIN
UPDATE team_has_game
SET position=2
WHERE idgame=gid
AND idteam NOT IN(
SELECT * FROM
	(
		SELECT team.idteam
		FROM team
		JOIN player ON team.idteam=player.idteam
		WHERE team.idteam IN (
			SELECT team.idteam
			FROM team
			JOIN team_has_game as thg ON thg.idteam=team.idteam
			JOIN game ON game.idgame=thg.idgame
			WHERE game.idgame=gid
		)
		GROUP BY team.idteam
		ORDER BY AVG(player.age) DESC
		LIMIT 1
	) as t1
)
;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure setallgames
-- -----------------------------------------------------

DELIMITER $$
USE `petanca`$$
CREATE PROCEDURE `setallgames` ()
BEGIN
SET @i = 1;
SET @max = (SELECT COUNT(*) FROM game);
WHILE (@i <= @max) DO
    CALL setwinner(@i);
    CALL setloser(@i);
    SET @i = @i + 1;
END WHILE;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
